application: broappapi
module: api
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: broapi.application

libraries:
- name: endpoints
  version: 1.0